language: csharp

script:

  - xbuild /p:Configuration=Debug SROM.sln

before_install:

  - sudo apt-get install nunit-console

before_script:

  - nuget restore SROM.sln

after_script:

- nunit-console SROM/bin/Debug/SROM.exe
